baseURL: http://www.triumphlarp.org/
title: TRIUMPH
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1

MetaDataFormat: yaml

markup:
  goldmark:
    extensions:
      typographer: true
    renderer:
      unsafe: true

outputFormats:
  printhtml:
    baseName: index
    mediaType: text/html
    path: print
    notAlternative: true

outputs:
  page:
    - HTML
  section:
    - HTML

menu:
  main:
  - name: Home
    url: /index.html
    weight: 1
  - name: Practical
    url: /practical/
    weight: 2
  - name: Play
    url: /play/
    weight: 3
  - name: Setting
    url: /setting/
    weight: 4
  - name: FAQ
    url: /faq/
    weight: 5

deployment:
  targets:
    name: prod
    URL: s3://www.triumphlarp.org?region=us-east-1
